Implement the draft of the dynamic adjustment of weights
MSUSEL/msusel-pique-visualizer pull request #13
Opened 2024-01-24 05:10 UTC by echozzy629

2024-01-25 22:01 UTC, devjeetr requested changes

2024-01-25 22:01 UTC, devjeetr commented on package.json
> +    "@react-three/fiber": "^8.15.14",
are we using this?

2024-01-25 22:01 UTC, devjeetr commented on package.json
> +    "@mui/material": "^5.15.6",
these as well

2024-01-25 22:01 UTC, devjeetr commented on package.json
> +    "three": "^0.160.1",
are we using this?

2024-01-25 22:01 UTC, devjeetr commented on package.json
> +    "react-select": "^5.8.0",
are we using this?

2024-01-26 00:01 UTC, echozzy629 commented on package.json
> +    "react-select": "^5.8.0",
removed

2024-01-26 00:01 UTC, echozzy629 commented on package.json
> +    "three": "^0.160.1",
removed

2024-01-26 00:01 UTC, echozzy629 commented on package.json
> +    "@mui/material": "^5.15.6",
removed

2024-01-26 00:01 UTC, echozzy629 commented on package.json
> +    "@react-three/fiber": "^8.15.14",
removed

2024-01-29 22:46 UTC, merged